apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: argocd
data:
  argocd.conf: |
    server {
        listen 80;
        server_name argocd.local; # nebo použijte IP adresu

        location / {
            proxy_pass http://argocd-server.argocd.svc.cluster.local:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }