apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: it-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
        - name: it-tools
          image: corentinth/it-tools:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: it-tools-data
              mountPath: /data
      volumes:
        - name: it-tools-data
          persistentVolumeClaim:
            claimName: it-tools-pvc