apiVersion: v1
kind: Service
metadata:
  name: it-tools
  namespace: it-tools
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32004  # Port pro přístup zvenčí
  selector:
    app: it-tools