apiVersion: v1
kind: Service
metadata:
  name: it-tools
  namespace: it-tools
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32004  # Port pro přístup zvenčí
  selector:
    app: it-tools