apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 32001  # Volitelně, pokud chcete přístup přes NodePort
  selector:
    app: uptime-kuma