apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-storage
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard